[toolchain]
channel = "1.90.0"
# channel = "nightly-2025-11-09"
components = ["rust-src", "rustfmt", "rust-analyzer", "clippy"]
targets = ["wasm32-unknown-unknown", "wasm32v1-none"]
profile = "minimal"
